/* Verilog module instantiation template generated by SCUBA Diamond Version 3.4.0.80 */
/* Module Version: 5.7 */
/* Tue Jun 23 20:24:11 2015 */

/* parameterized module instance */
AMIV_PLL __ (.CLKI( ), .CLKOP( ));
